services:
  db:
    container_name: postgres
    image: 'postgres:14.5-alpine'
    ## hack to enable network using direct hostname
    hostname: postgres-local
    restart: always
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: todo-api
    build: .
    image: todo-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
volumes:
  pg_data:

networks:
  backend:
    name: backend-network
    driver: bridge
