services:
  db:
    container_name: postgres
    image: 'postgres:14.5-alpine'
    ## hack to enable network using direct hostname
    hostname: postgres-local
    restart: always
    environment:
      - DATABASE_HOST=${PG_DB_HOST}
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    ports:
      - ${PG_DB_LOCAL_PORT}:${PG_DB_DOCKER_PORT}
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    container_name: todo-api
    build: .
    image: todo-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: on-failure
    environment:
      DB_HOST: ${PG_DB_HOST}
      DB_PORT: ${PG_DB_DOCKER_PORT}
      DB_USER: ${PG_DB_USER}
      DB_PASSWORD: ${PG_DB_PASSWORD}
      DB_NAME: ${PG_DB_NAME}
volumes:
  db:

networks:
  backend:
    name: backend-network
    driver: bridge
